#!/bin/bash

# Based on http://stackoverflow.com/questions/3462955/putting-git-hooks-into-repository#3464399

HOOK_NAMES="applypatch-msg pre-applypatch post-applypatch pre-commit prepare-commit-msg commit-msg post-commit pre-rebase post-checkout post-merge pre-push pre-receive update post-receive post-update pre-auto-gc post-rewrite"

GIT_DIR=$(git rev-parse --git-dir)
REPO_ROOT=$(git rev-parse --show-toplevel)
HOOK_DIR=$GIT_DIR/hooks

for hook in $HOOK_NAMES; do
	# If the hook already exists, is executable, and is not a symlink.
	if [ ! -h $HOOK_DIR/$hook -a -x $HOOK_DIR/$hook ]; then
		mv $HOOK_DIR/$hook $HOOK_DIR/$hook.local
	fi

	# Create the symlink, overwriting the file if it exists.
	ln -s -f $REPO_ROOT/devtools/any-git-hook $HOOK_DIR/$hook
done
